export const CSS_COLOR_NAMES = [
  `aliceblue`,
  `antiquewhite`,
  `aqua`,
  `aquamarine`,
  `azure`,
  `beige`,
  `bisque`,
  `black`,
  `blanchedalmond`,
  `blue`,
  `blueviolet`,
  `brown`,
  `burlywood`,
  `cadetblue`,
  `chartreuse`,
  `chocolate`,
  `coral`,
  `cornflowerblue`,
  `cornsilk`,
  `crimson`,
  `cyan`,
  `darkblue`,
  `darkcyan`,
  `darkgoldenrod`,
  `darkgray`,
  `darkgreen`,
  `darkgrey`,
  `darkkhaki`,
  `darkmagenta`,
  `darkolivegreen`,
  `darkorange`,
  `darkorchid`,
  `darkred`,
  `darksalmon`,
  `darkseagreen`,
  `darkslateblue`,
  `darkslategray`,
  `darkslategrey`,
  `darkturquoise`,
  `darkviolet`,
  `deeppink`,
  `deepskyblue`,
  `dimgray`,
  `dimgrey`,
  `dodgerblue`,
  `firebrick`,
  `floralwhite`,
  `forestgreen`,
  `fuchsia`,
  `gainsboro`,
  `ghostwhite`,
  `gold`,
  `goldenrod`,
  `gray`,
  `green`,
  `greenyellow`,
  `grey`,
  `honeydew`,
  `hotpink`,
  `indianred`,
  `indigo`,
  `ivory`,
  `khaki`,
  `lavender`,
  `lavenderblush`,
  `lawngreen`,
  `lemonchiffon`,
  `lightblue`,
  `lightcoral`,
  `lightcyan`,
  `lightgoldenrodyellow`,
  `lightgray`,
  `lightgreen`,
  `lightgrey`,
  `lightpink`,
  `lightsalmon`,
  `lightseagreen`,
  `lightskyblue`,
  `lightslategray`,
  `lightslategrey`,
  `lightsteelblue`,
  `lightyellow`,
  `lime`,
  `limegreen`,
  `linen`,
  `magenta`,
  `maroon`,
  `mediumaquamarine`,
  `mediumblue`,
  `mediumorchid`,
  `mediumpurple`,
  `mediumseagreen`,
  `mediumslateblue`,
  `mediumspringgreen`,
  `mediumturquoise`,
  `mediumvioletred`,
  `midnightblue`,
  `mintcream`,
  `mistyrose`,
  `moccasin`,
  `navajowhite`,
  `navy`,
  `oldlace`,
  `olive`,
  `olivedrab`,
  `orange`,
  `orangered`,
  `orchid`,
  `palegoldenrod`,
  `palegreen`,
  `paleturquoise`,
  `palevioletred`,
  `papayawhip`,
  `peachpuff`,
  `peru`,
  `pink`,
  `plum`,
  `powderblue`,
  `purple`,
  `rebeccapurple`,
  `red`,
  `rosybrown`,
  `royalblue`,
  `saddlebrown`,
  `salmon`,
  `sandybrown`,
  `seagreen`,
  `seashell`,
  `sienna`,
  `silver`,
  `skyblue`,
  `slateblue`,
  `slategray`,
  `slategrey`,
  `snow`,
  `springgreen`,
  `steelblue`,
  `tan`,
  `teal`,
  `thistle`,
  `tomato`,
  `transparent`,
  `turquoise`,
  `violet`,
  `wheat`,
  `white`,
  `whitesmoke`,
  `yellow`,
  `yellowgreen`,
  `ALICEBLUE`,
  `ANTIQUEWHITE`,
  `AQUA`,
  `AQUAMARINE`,
  `AZURE`,
  `BEIGE`,
  `BISQUE`,
  `BLACK`,
  `BLANCHEDALMOND`,
  `BLUE`,
  `BLUEVIOLET`,
  `BROWN`,
  `BURLYWOOD`,
  `CADETBLUE`,
  `CHARTREUSE`,
  `CHOCOLATE`,
  `CORAL`,
  `CORNFLOWERBLUE`,
  `CORNSILK`,
  `CRIMSON`,
  `CYAN`,
  `DARKBLUE`,
  `DARKCYAN`,
  `DARKGOLDENROD`,
  `DARKGRAY`,
  `DARKGREEN`,
  `DARKGREY`,
  `DARKKHAKI`,
  `DARKMAGENTA`,
  `DARKOLIVEGREEN`,
  `DARKORANGE`,
  `DARKORCHID`,
  `DARKRED`,
  `DARKSALMON`,
  `DARKSEAGREEN`,
  `DARKSLATEBLUE`,
  `DARKSLATEGRAY`,
  `DARKSLATEGREY`,
  `DARKTURQUOISE`,
  `DARKVIOLET`,
  `DEEPPINK`,
  `DEEPSKYBLUE`,
  `DIMGRAY`,
  `DIMGREY`,
  `DODGERBLUE`,
  `FIREBRICK`,
  `FLORALWHITE`,
  `FORESTGREEN`,
  `FUCHSIA`,
  `GAINSBORO`,
  `GHOSTWHITE`,
  `GOLD`,
  `GOLDENROD`,
  `GRAY`,
  `GREEN`,
  `GREENYELLOW`,
  `GREY`,
  `HONEYDEW`,
  `HOTPINK`,
  `INDIANRED`,
  `INDIGO`,
  `IVORY`,
  `KHAKI`,
  `LAVENDER`,
  `LAVENDERBLUSH`,
  `LAWNGREEN`,
  `LEMONCHIFFON`,
  `LIGHTBLUE`,
  `LIGHTCORAL`,
  `LIGHTCYAN`,
  `LIGHTGOLDENRODYELLOW`,
  `LIGHTGRAY`,
  `LIGHTGREEN`,
  `LIGHTGREY`,
  `LIGHTPINK`,
  `LIGHTSALMON`,
  `LIGHTSEAGREEN`,
  `LIGHTSKYBLUE`,
  `LIGHTSLATEGRAY`,
  `LIGHTSLATEGREY`,
  `LIGHTSTEELBLUE`,
  `LIGHTYELLOW`,
  `LIME`,
  `LIMEGREEN`,
  `LINEN`,
  `MAGENTA`,
  `MAROON`,
  `MEDIUMAQUAMARINE`,
  `MEDIUMBLUE`,
  `MEDIUMORCHID`,
  `MEDIUMPURPLE`,
  `MEDIUMSEAGREEN`,
  `MEDIUMSLATEBLUE`,
  `MEDIUMSPRINGGREEN`,
  `MEDIUMTURQUOISE`,
  `MEDIUMVIOLETRED`,
  `MIDNIGHTBLUE`,
  `MINTCREAM`,
  `MISTYROSE`,
  `MOCCASIN`,
  `NAVAJOWHITE`,
  `NAVY`,
  `OLDLACE`,
  `OLIVE`,
  `OLIVEDRAB`,
  `ORANGE`,
  `ORANGERED`,
  `ORCHID`,
  `PALEGOLDENROD`,
  `PALEGREEN`,
  `PALETURQUOISE`,
  `PALEVIOLETRED`,
  `PAPAYAWHIP`,
  `PEACHPUFF`,
  `PERU`,
  `PINK`,
  `PLUM`,
  `POWDERBLUE`,
  `PURPLE`,
  `REBECCAPURPLE`,
  `RED`,
  `ROSYBROWN`,
  `ROYALBLUE`,
  `SADDLEBROWN`,
  `SALMON`,
  `SANDYBROWN`,
  `SEAGREEN`,
  `SEASHELL`,
  `SIENNA`,
  `SILVER`,
  `SKYBLUE`,
  `SLATEBLUE`,
  `SLATEGRAY`,
  `SLATEGREY`,
  `SNOW`,
  `SPRINGGREEN`,
  `STEELBLUE`,
  `TAN`,
  `TEAL`,
  `THISTLE`,
  `TOMATO`,
  `TRANSPARENT`,
  `TURQUOISE`,
  `VIOLET`,
  `WHEAT`,
  `WHITE`,
  `WHITESMOKE`,
  `YELLOW`,
  `YELLOWGREEN`,
];

export const CSS_COLOR_MAP = {
  aliceblue: `rgb(${0xf0}, ${0xf8}, ${0xff})`,
  antiquewhite: `rgb(${0xfa}, ${0xeb}, ${0xd7})`,
  aqua: `rgb(${0x00}, ${0xff}, ${0xff})`,
  aquamarine: `rgb(${0x7f}, ${0xff}, ${0xd4})`,
  azure: `rgb(${0xf0}, ${0xff}, ${0xff})`,
  beige: `rgb(${0xf5}, ${0xf5}, ${0xdc})`,
  bisque: `rgb(${0xff}, ${0xe4}, ${0xc4})`,
  black: `rgb(${0x00}, ${0x00}, ${0x00})`,
  blanchedalmond: `rgb(${0xff}, ${0xeb}, ${0xcd})`,
  blue: `rgb(${0x00}, ${0x00}, ${0xff})`,
  blueviolet: `rgb(${0x8a}, ${0x2b}, ${0xe2})`,
  brown: `rgb(${0xa5}, ${0x2a}, ${0x2a})`,
  burlywood: `rgb(${0xde}, ${0xb8}, ${0x87})`,
  cadetblue: `rgb(${0x5f}, ${0x9e}, ${0xa0})`,
  chartreuse: `rgb(${0x7f}, ${0xff}, ${0x00})`,
  chocolate: `rgb(${0xd2}, ${0x69}, ${0x1e})`,
  coral: `rgb(${0xff}, ${0x7f}, ${0x50})`,
  cornflowerblue: `rgb(${0x64}, ${0x95}, ${0xed})`,
  cornsilk: `rgb(${0xff}, ${0xf8}, ${0xdc})`,
  crimson: `rgb(${0xdc}, ${0x14}, ${0x3c})`,
  cyan: `rgb(${0x00}, ${0xff}, ${0xff})`,
  darkblue: `rgb(${0x00}, ${0x00}, ${0x8b})`,
  darkcyan: `rgb(${0x00}, ${0x8b}, ${0x8b})`,
  darkgoldenrod: `rgb(${0xb8}, ${0x86}, ${0x0b})`,
  darkgray: `rgb(${0xa9}, ${0xa9}, ${0xa9})`,
  darkgreen: `rgb(${0x00}, ${0x64}, ${0x00})`,
  darkgrey: `rgb(${0xa9}, ${0xa9}, ${0xa9})`,
  darkkhaki: `rgb(${0xbd}, ${0xb7}, ${0x6b})`,
  darkmagenta: `rgb(${0x8b}, ${0x00}, ${0x8b})`,
  darkolivegreen: `rgb(${0x55}, ${0x6b}, ${0x2f})`,
  darkorange: `rgb(${0xff}, ${0x8c}, ${0x00})`,
  darkorchid: `rgb(${0x99}, ${0x32}, ${0xcc})`,
  darkred: `rgb(${0x8b}, ${0x00}, ${0x00})`,
  darksalmon: `rgb(${0xe9}, ${0x96}, ${0x7a})`,
  darkseagreen: `rgb(${0x8f}, ${0xbc}, ${0x8f})`,
  darkslateblue: `rgb(${0x48}, ${0x3d}, ${0x8b})`,
  darkslategray: `rgb(${0x2f}, ${0x4f}, ${0x4f})`,
  darkslategrey: `rgb(${0x2f}, ${0x4f}, ${0x4f})`,
  darkturquoise: `rgb(${0x00}, ${0xce}, ${0xd1})`,
  darkviolet: `rgb(${0x94}, ${0x00}, ${0xd3})`,
  deeppink: `rgb(${0xff}, ${0x14}, ${0x93})`,
  deepskyblue: `rgb(${0x00}, ${0xbf}, ${0xff})`,
  dimgray: `rgb(${0x69}, ${0x69}, ${0x69})`,
  dimgrey: `rgb(${0x69}, ${0x69}, ${0x69})`,
  dodgerblue: `rgb(${0x1e}, ${0x90}, ${0xff})`,
  firebrick: `rgb(${0xb2}, ${0x22}, ${0x22})`,
  floralwhite: `rgb(${0xff}, ${0xfa}, ${0xf0})`,
  forestgreen: `rgb(${0x22}, ${0x8b}, ${0x22})`,
  fuchsia: `rgb(${0xff}, ${0x00}, ${0xff})`,
  gainsboro: `rgb(${0xdc}, ${0xdc}, ${0xdc})`,
  ghostwhite: `rgb(${0xf8}, ${0xf8}, ${0xff})`,
  gold: `rgb(${0xff}, ${0xd7}, ${0x00})`,
  goldenrod: `rgb(${0xda}, ${0xa5}, ${0x20})`,
  gray: `rgb(${0x80}, ${0x80}, ${0x80})`,
  green: `rgb(${0x00}, ${0x80}, ${0x00})`,
  greenyellow: `rgb(${0xad}, ${0xff}, ${0x2f})`,
  grey: `rgb(${0x80}, ${0x80}, ${0x80})`,
  honeydew: `rgb(${0xf0}, ${0xff}, ${0xf0})`,
  hotpink: `rgb(${0xff}, ${0x69}, ${0xb4})`,
  indianred: `rgb(${0xcd}, ${0x5c}, ${0x5c})`,
  indigo: `rgb(${0x4b}, ${0x00}, ${0x82})`,
  ivory: `rgb(${0xff}, ${0xff}, ${0xf0})`,
  khaki: `rgb(${0xf0}, ${0xe6}, ${0x8c})`,
  lavender: `rgb(${0xe6}, ${0xe6}, ${0xfa})`,
  lavenderblush: `rgb(${0xff}, ${0xf0}, ${0xf5})`,
  lawngreen: `rgb(${0x7c}, ${0xfc}, ${0x00})`,
  lemonchiffon: `rgb(${0xff}, ${0xfa}, ${0xcd})`,
  lightblue: `rgb(${0xad}, ${0xd8}, ${0xe6})`,
  lightcoral: `rgb(${0xf0}, ${0x80}, ${0x80})`,
  lightcyan: `rgb(${0xe0}, ${0xff}, ${0xff})`,
  lightgoldenrodyellow: `rgb(${0xfa}, ${0xfa}, ${0xd2})`,
  lightgray: `rgb(${0xd3}, ${0xd3}, ${0xd3})`,
  lightgreen: `rgb(${0x90}, ${0xee}, ${0x90})`,
  lightgrey: `rgb(${0xd3}, ${0xd3}, ${0xd3})`,
  lightpink: `rgb(${0xff}, ${0xb6}, ${0xc1})`,
  lightsalmon: `rgb(${0xff}, ${0xa0}, ${0x7a})`,
  lightseagreen: `rgb(${0x20}, ${0xb2}, ${0xaa})`,
  lightskyblue: `rgb(${0x87}, ${0xce}, ${0xfa})`,
  lightslategray: `rgb(${0x77}, ${0x88}, ${0x99})`,
  lightslategrey: `rgb(${0x77}, ${0x88}, ${0x99})`,
  lightsteelblue: `rgb(${0xb0}, ${0xc4}, ${0xde})`,
  lightyellow: `rgb(${0xff}, ${0xff}, ${0xe0})`,
  lime: `rgb(${0x00}, ${0xff}, ${0x00})`,
  limegreen: `rgb(${0x32}, ${0xcd}, ${0x32})`,
  linen: `rgb(${0xfa}, ${0xf0}, ${0xe6})`,
  magenta: `rgb(${0xff}, ${0x00}, ${0xff})`,
  maroon: `rgb(${0x80}, ${0x00}, ${0x00})`,
  mediumaquamarine: `rgb(${0x66}, ${0xcd}, ${0xaa})`,
  mediumblue: `rgb(${0x00}, ${0x00}, ${0xcd})`,
  mediumorchid: `rgb(${0xba}, ${0x55}, ${0xd3})`,
  mediumpurple: `rgb(${0x93}, ${0x70}, ${0xdb})`,
  mediumseagreen: `rgb(${0x3c}, ${0xb3}, ${0x71})`,
  mediumslateblue: `rgb(${0x7b}, ${0x68}, ${0xee})`,
  mediumspringgreen: `rgb(${0x00}, ${0xfa}, ${0x9a})`,
  mediumturquoise: `rgb(${0x48}, ${0xd1}, ${0xcc})`,
  mediumvioletred: `rgb(${0xc7}, ${0x15}, ${0x85})`,
  midnightblue: `rgb(${0x19}, ${0x19}, ${0x70})`,
  mintcream: `rgb(${0xf5}, ${0xff}, ${0xfa})`,
  mistyrose: `rgb(${0xff}, ${0xe4}, ${0xe1})`,
  moccasin: `rgb(${0xff}, ${0xe4}, ${0xb5})`,
  navajowhite: `rgb(${0xff}, ${0xde}, ${0xad})`,
  navy: `rgb(${0x00}, ${0x00}, ${0x80})`,
  oldlace: `rgb(${0xfd}, ${0xf5}, ${0xe6})`,
  olive: `rgb(${0x80}, ${0x80}, ${0x00})`,
  olivedrab: `rgb(${0x6b}, ${0x8e}, ${0x23})`,
  orange: `rgb(${0xff}, ${0xa5}, ${0x00})`,
  orangered: `rgb(${0xff}, ${0x45}, ${0x00})`,
  orchid: `rgb(${0xda}, ${0x70}, ${0xd6})`,
  palegoldenrod: `rgb(${0xee}, ${0xe8}, ${0xaa})`,
  palegreen: `rgb(${0x98}, ${0xfb}, ${0x98})`,
  paleturquoise: `rgb(${0xaf}, ${0xee}, ${0xee})`,
  palevioletred: `rgb(${0xdb}, ${0x70}, ${0x93})`,
  papayawhip: `rgb(${0xff}, ${0xef}, ${0xd5})`,
  peachpuff: `rgb(${0xff}, ${0xda}, ${0xb9})`,
  peru: `rgb(${0xcd}, ${0x85}, ${0x3f})`,
  pink: `rgb(${0xff}, ${0xc0}, ${0xcb})`,
  plum: `rgb(${0xdd}, ${0xa0}, ${0xdd})`,
  powderblue: `rgb(${0xb0}, ${0xe0}, ${0xe6})`,
  purple: `rgb(${0x80}, ${0x00}, ${0x80})`,
  rebeccapurple: `rgb(${0x66}, ${0x33}, ${0x99})`,
  red: `rgb(${0xff}, ${0x00}, ${0x00})`,
  rosybrown: `rgb(${0xbc}, ${0x8f}, ${0x8f})`,
  royalblue: `rgb(${0x41}, ${0x69}, ${0xe1})`,
  saddlebrown: `rgb(${0x8b}, ${0x45}, ${0x13})`,
  salmon: `rgb(${0xfa}, ${0x80}, ${0x72})`,
  sandybrown: `rgb(${0xf4}, ${0xa4}, ${0x60})`,
  seagreen: `rgb(${0x2e}, ${0x8b}, ${0x57})`,
  seashell: `rgb(${0xff}, ${0xf5}, ${0xee})`,
  sienna: `rgb(${0xa0}, ${0x52}, ${0x2d})`,
  silver: `rgb(${0xc0}, ${0xc0}, ${0xc0})`,
  skyblue: `rgb(${0x87}, ${0xce}, ${0xeb})`,
  slateblue: `rgb(${0x6a}, ${0x5a}, ${0xcd})`,
  slategray: `rgb(${0x70}, ${0x80}, ${0x90})`,
  slategrey: `rgb(${0x70}, ${0x80}, ${0x90})`,
  snow: `rgb(${0xff}, ${0xfa}, ${0xfa})`,
  springgreen: `rgb(${0x00}, ${0xff}, ${0x7f})`,
  steelblue: `rgb(${0x46}, ${0x82}, ${0xb4})`,
  tan: `rgb(${0xd2}, ${0xb4}, ${0x8c})`,
  teal: `rgb(${0x00}, ${0x80}, ${0x80})`,
  thistle: `rgb(${0xd8}, ${0xbf}, ${0xd8})`,
  tomato: `rgb(${0xff}, ${0x63}, ${0x47})`,
  transparent: `rgba(0,0,0,0)`,
  turquoise: `rgb(${0x40}, ${0xe0}, ${0xd0})`,
  violet: `rgb(${0xee}, ${0x82}, ${0xee})`,
  wheat: `rgb(${0xf5}, ${0xde}, ${0xb3})`,
  white: `rgb(${0xff}, ${0xff}, ${0xff})`,
  whitesmoke: `rgb(${0xf5}, ${0xf5}, ${0xf5})`,
  yellow: `rgb(${0xff}, ${0xff}, ${0x00})`,
  yellowgreen: `rgb(${0x9a}, ${0xcd}, ${0x32})`,
  // capital
  ALICEBLUE: `rgb(${0xf0}, ${0xf8}, ${0xff})`,
  ANTIQUEWHITE: `rgb(${0xfa}, ${0xeb}, ${0xd7})`,
  AQUA: `rgb(${0x00}, ${0xff}, ${0xff})`,
  AQUAMARINE: `rgb(${0x7f}, ${0xff}, ${0xd4})`,
  AZURE: `rgb(${0xf0}, ${0xff}, ${0xff})`,
  BEIGE: `rgb(${0xf5}, ${0xf5}, ${0xdc})`,
  BISQUE: `rgb(${0xff}, ${0xe4}, ${0xc4})`,
  BLACK: `rgb(${0x00}, ${0x00}, ${0x00})`,
  BLANCHEDALMOND: `rgb(${0xff}, ${0xeb}, ${0xcd})`,
  BLUE: `rgb(${0x00}, ${0x00}, ${0xff})`,
  BLUEVIOLET: `rgb(${0x8a}, ${0x2b}, ${0xe2})`,
  BROWN: `rgb(${0xa5}, ${0x2a}, ${0x2a})`,
  BURLYWOOD: `rgb(${0xde}, ${0xb8}, ${0x87})`,
  CADETBLUE: `rgb(${0x5f}, ${0x9e}, ${0xa0})`,
  CHARTREUSE: `rgb(${0x7f}, ${0xff}, ${0x00})`,
  CHOCOLATE: `rgb(${0xd2}, ${0x69}, ${0x1e})`,
  CORAL: `rgb(${0xff}, ${0x7f}, ${0x50})`,
  CORNFLOWERBLUE: `rgb(${0x64}, ${0x95}, ${0xed})`,
  CORNSILK: `rgb(${0xff}, ${0xf8}, ${0xdc})`,
  CRIMSON: `rgb(${0xdc}, ${0x14}, ${0x3c})`,
  CYAN: `rgb(${0x00}, ${0xff}, ${0xff})`,
  DARKBLUE: `rgb(${0x00}, ${0x00}, ${0x8b})`,
  DARKCYAN: `rgb(${0x00}, ${0x8b}, ${0x8b})`,
  DARKGOLDENROD: `rgb(${0xb8}, ${0x86}, ${0x0b})`,
  DARKGRAY: `rgb(${0xa9}, ${0xa9}, ${0xa9})`,
  DARKGREEN: `rgb(${0x00}, ${0x64}, ${0x00})`,
  DARKGREY: `rgb(${0xa9}, ${0xa9}, ${0xa9})`,
  DARKKHAKI: `rgb(${0xbd}, ${0xb7}, ${0x6b})`,
  DARKMAGENTA: `rgb(${0x8b}, ${0x00}, ${0x8b})`,
  DARKOLIVEGREEN: `rgb(${0x55}, ${0x6b}, ${0x2f})`,
  DARKORANGE: `rgb(${0xff}, ${0x8c}, ${0x00})`,
  DARKORCHID: `rgb(${0x99}, ${0x32}, ${0xcc})`,
  DARKRED: `rgb(${0x8b}, ${0x00}, ${0x00})`,
  DARKSALMON: `rgb(${0xe9}, ${0x96}, ${0x7a})`,
  DARKSEAGREEN: `rgb(${0x8f}, ${0xbc}, ${0x8f})`,
  DARKSLATEBLUE: `rgb(${0x48}, ${0x3d}, ${0x8b})`,
  DARKSLATEGRAY: `rgb(${0x2f}, ${0x4f}, ${0x4f})`,
  DARKSLATEGREY: `rgb(${0x2f}, ${0x4f}, ${0x4f})`,
  DARKTURQUOISE: `rgb(${0x00}, ${0xce}, ${0xd1})`,
  DARKVIOLET: `rgb(${0x94}, ${0x00}, ${0xd3})`,
  DEEPPINK: `rgb(${0xff}, ${0x14}, ${0x93})`,
  DEEPSKYBLUE: `rgb(${0x00}, ${0xbf}, ${0xff})`,
  DIMGRAY: `rgb(${0x69}, ${0x69}, ${0x69})`,
  DIMGREY: `rgb(${0x69}, ${0x69}, ${0x69})`,
  DODGERBLUE: `rgb(${0x1e}, ${0x90}, ${0xff})`,
  FIREBRICK: `rgb(${0xb2}, ${0x22}, ${0x22})`,
  FLORALWHITE: `rgb(${0xff}, ${0xfa}, ${0xf0})`,
  FORESTGREEN: `rgb(${0x22}, ${0x8b}, ${0x22})`,
  FUCHSIA: `rgb(${0xff}, ${0x00}, ${0xff})`,
  GAINSBORO: `rgb(${0xdc}, ${0xdc}, ${0xdc})`,
  GHOSTWHITE: `rgb(${0xf8}, ${0xf8}, ${0xff})`,
  GOLD: `rgb(${0xff}, ${0xd7}, ${0x00})`,
  GOLDENROD: `rgb(${0xda}, ${0xa5}, ${0x20})`,
  GRAY: `rgb(${0x80}, ${0x80}, ${0x80})`,
  GREEN: `rgb(${0x00}, ${0x80}, ${0x00})`,
  GREENYELLOW: `rgb(${0xad}, ${0xff}, ${0x2f})`,
  GREY: `rgb(${0x80}, ${0x80}, ${0x80})`,
  HONEYDEW: `rgb(${0xf0}, ${0xff}, ${0xf0})`,
  HOTPINK: `rgb(${0xff}, ${0x69}, ${0xb4})`,
  INDIANRED: `rgb(${0xcd}, ${0x5c}, ${0x5c})`,
  INDIGO: `rgb(${0x4b}, ${0x00}, ${0x82})`,
  IVORY: `rgb(${0xff}, ${0xff}, ${0xf0})`,
  KHAKI: `rgb(${0xf0}, ${0xe6}, ${0x8c})`,
  LAVENDER: `rgb(${0xe6}, ${0xe6}, ${0xfa})`,
  LAVENDERBLUSH: `rgb(${0xff}, ${0xf0}, ${0xf5})`,
  LAWNGREEN: `rgb(${0x7c}, ${0xfc}, ${0x00})`,
  LEMONCHIFFON: `rgb(${0xff}, ${0xfa}, ${0xcd})`,
  LIGHTBLUE: `rgb(${0xad}, ${0xd8}, ${0xe6})`,
  LIGHTCORAL: `rgb(${0xf0}, ${0x80}, ${0x80})`,
  LIGHTCYAN: `rgb(${0xe0}, ${0xff}, ${0xff})`,
  LIGHTGOLDENRODYELLOW: `rgb(${0xfa}, ${0xfa}, ${0xd2})`,
  LIGHTGRAY: `rgb(${0xd3}, ${0xd3}, ${0xd3})`,
  LIGHTGREEN: `rgb(${0x90}, ${0xee}, ${0x90})`,
  LIGHTGREY: `rgb(${0xd3}, ${0xd3}, ${0xd3})`,
  LIGHTPINK: `rgb(${0xff}, ${0xb6}, ${0xc1})`,
  LIGHTSALMON: `rgb(${0xff}, ${0xa0}, ${0x7a})`,
  LIGHTSEAGREEN: `rgb(${0x20}, ${0xb2}, ${0xaa})`,
  LIGHTSKYBLUE: `rgb(${0x87}, ${0xce}, ${0xfa})`,
  LIGHTSLATEGRAY: `rgb(${0x77}, ${0x88}, ${0x99})`,
  LIGHTSLATEGREY: `rgb(${0x77}, ${0x88}, ${0x99})`,
  LIGHTSTEELBLUE: `rgb(${0xb0}, ${0xc4}, ${0xde})`,
  LIGHTYELLOW: `rgb(${0xff}, ${0xff}, ${0xe0})`,
  LIME: `rgb(${0x00}, ${0xff}, ${0x00})`,
  LIMEGREEN: `rgb(${0x32}, ${0xcd}, ${0x32})`,
  LINEN: `rgb(${0xfa}, ${0xf0}, ${0xe6})`,
  MAGENTA: `rgb(${0xff}, ${0x00}, ${0xff})`,
  MAROON: `rgb(${0x80}, ${0x00}, ${0x00})`,
  MEDIUMAQUAMARINE: `rgb(${0x66}, ${0xcd}, ${0xaa})`,
  MEDIUMBLUE: `rgb(${0x00}, ${0x00}, ${0xcd})`,
  MEDIUMORCHID: `rgb(${0xba}, ${0x55}, ${0xd3})`,
  MEDIUMPURPLE: `rgb(${0x93}, ${0x70}, ${0xdb})`,
  MEDIUMSEAGREEN: `rgb(${0x3c}, ${0xb3}, ${0x71})`,
  MEDIUMSLATEBLUE: `rgb(${0x7b}, ${0x68}, ${0xee})`,
  MEDIUMSPRINGGREEN: `rgb(${0x00}, ${0xfa}, ${0x9a})`,
  MEDIUMTURQUOISE: `rgb(${0x48}, ${0xd1}, ${0xcc})`,
  MEDIUMVIOLETRED: `rgb(${0xc7}, ${0x15}, ${0x85})`,
  MIDNIGHTBLUE: `rgb(${0x19}, ${0x19}, ${0x70})`,
  MINTCREAM: `rgb(${0xf5}, ${0xff}, ${0xfa})`,
  MISTYROSE: `rgb(${0xff}, ${0xe4}, ${0xe1})`,
  MOCCASIN: `rgb(${0xff}, ${0xe4}, ${0xb5})`,
  NAVAJOWHITE: `rgb(${0xff}, ${0xde}, ${0xad})`,
  NAVY: `rgb(${0x00}, ${0x00}, ${0x80})`,
  OLDLACE: `rgb(${0xfd}, ${0xf5}, ${0xe6})`,
  OLIVE: `rgb(${0x80}, ${0x80}, ${0x00})`,
  OLIVEDRAB: `rgb(${0x6b}, ${0x8e}, ${0x23})`,
  ORANGE: `rgb(${0xff}, ${0xa5}, ${0x00})`,
  ORANGERED: `rgb(${0xff}, ${0x45}, ${0x00})`,
  ORCHID: `rgb(${0xda}, ${0x70}, ${0xd6})`,
  PALEGOLDENROD: `rgb(${0xee}, ${0xe8}, ${0xaa})`,
  PALEGREEN: `rgb(${0x98}, ${0xfb}, ${0x98})`,
  PALETURQUOISE: `rgb(${0xaf}, ${0xee}, ${0xee})`,
  PALEVIOLETRED: `rgb(${0xdb}, ${0x70}, ${0x93})`,
  PAPAYAWHIP: `rgb(${0xff}, ${0xef}, ${0xd5})`,
  PEACHPUFF: `rgb(${0xff}, ${0xda}, ${0xb9})`,
  PERU: `rgb(${0xcd}, ${0x85}, ${0x3f})`,
  PINK: `rgb(${0xff}, ${0xc0}, ${0xcb})`,
  PLUM: `rgb(${0xdd}, ${0xa0}, ${0xdd})`,
  POWDERBLUE: `rgb(${0xb0}, ${0xe0}, ${0xe6})`,
  PURPLE: `rgb(${0x80}, ${0x00}, ${0x80})`,
  REBECCAPURPLE: `rgb(${0x66}, ${0x33}, ${0x99})`,
  RED: `rgb(${0xff}, ${0x00}, ${0x00})`,
  ROSYBROWN: `rgb(${0xbc}, ${0x8f}, ${0x8f})`,
  ROYALBLUE: `rgb(${0x41}, ${0x69}, ${0xe1})`,
  SADDLEBROWN: `rgb(${0x8b}, ${0x45}, ${0x13})`,
  SALMON: `rgb(${0xfa}, ${0x80}, ${0x72})`,
  SANDYBROWN: `rgb(${0xf4}, ${0xa4}, ${0x60})`,
  SEAGREEN: `rgb(${0x2e}, ${0x8b}, ${0x57})`,
  SEASHELL: `rgb(${0xff}, ${0xf5}, ${0xee})`,
  SIENNA: `rgb(${0xa0}, ${0x52}, ${0x2d})`,
  SILVER: `rgb(${0xc0}, ${0xc0}, ${0xc0})`,
  SKYBLUE: `rgb(${0x87}, ${0xce}, ${0xeb})`,
  SLATEBLUE: `rgb(${0x6a}, ${0x5a}, ${0xcd})`,
  SLATEGRAY: `rgb(${0x70}, ${0x80}, ${0x90})`,
  SLATEGREY: `rgb(${0x70}, ${0x80}, ${0x90})`,
  SNOW: `rgb(${0xff}, ${0xfa}, ${0xfa})`,
  SPRINGGREEN: `rgb(${0x00}, ${0xff}, ${0x7f})`,
  STEELBLUE: `rgb(${0x46}, ${0x82}, ${0xb4})`,
  TAN: `rgb(${0xd2}, ${0xb4}, ${0x8c})`,
  TEAL: `rgb(${0x00}, ${0x80}, ${0x80})`,
  THISTLE: `rgb(${0xd8}, ${0xbf}, ${0xd8})`,
  TOMATO: `rgb(${0xff}, ${0x63}, ${0x47})`,
  TRANSPARENT: `rgba(0,0,0,0)`,
  TURQUOISE: `rgb(${0x40}, ${0xe0}, ${0xd0})`,
  VIOLET: `rgb(${0xee}, ${0x82}, ${0xee})`,
  WHEAT: `rgb(${0xf5}, ${0xde}, ${0xb3})`,
  WHITE: `rgb(${0xff}, ${0xff}, ${0xff})`,
  WHITESMOKE: `rgb(${0xf5}, ${0xf5}, ${0xf5})`,
  YELLOW: `rgb(${0xff}, ${0xff}, ${0x00})`,
  YELLOWGREEN: `rgb(${0x9a}, ${0xcd}, ${0x32})`,
};
